---

- name: Create full clone VM from template
  community.general.proxmox_kvm:
    api_host: heimdall.akuadora.net
    api_user: root@pam
    api_password: "{{ heimdallroot }}"
    clone: "{{ templatename }}"
    vmid: "{{ templateid }}"
    name: "{{ nameofhost }}"
    node: heimdall
    storage: local
    full: true
    format: qcow2
    timeout: 500

- name: Wait 60 seconds for template to be cloned
  ansible.builtin.wait_for:
    timeout: 60

- name: Start cloned VM
  community.general.proxmox_kvm:
    api_host: heimdall.akuadora.net
    api_user: root@pam
    api_password: "{{ heimdallroot }}"
    name: "{{ nameofhost }}"
    node: heimdall
    state: started

- name: Wait 60 seconds for clone to be started
  ansible.builtin.wait_for:
    timeout: 60

...
