---

- name: Create full clone VM from template
  community.general.proxmox_kvm:
#    clone: spynal
    vmid: 100600
    name: "{{ nameofhost }}"
    node: heimdall
    storage: local
    full: true
    format: qcow2
    timeout: 500

...
